Update dotnet-workflow.yml

diff --git a/.github/workflows/dotnet-workflow.yml b/.github/workflows/dotnet-workflow.yml
--- a/.github/workflows/dotnet-workflow.yml
+++ b/.github/workflows/dotnet-workflow.yml
@@ -10,8 +10,12 @@ jobs:
   worflow:
     runs-on: ubuntu-latest
 
+    defaults:
+      run:
+        working-directory: ./TestProject
+
     env:
-      SOLUTION_PATH: ./TestProject/TestProject.sln
+      SOLUTION_NAME: TestProject.sln
     
     steps:
 
@@ -32,18 +36,18 @@ jobs:
         dotnet-version: 6.0.x
 
     - name: Echo
-      run: echo $SOLUTION_PATH
+      run: echo $SOLUTION_NAME
     
     - name: Restore dependencies
-      run: dotnet restore $SOLUTION_PATH
+      run: dotnet restore $SOLUTION_NAME
 
     - name: Build
-      run: dotnet build $SOLUTION_PATH --configuration Release --warnaserror
+      run: dotnet build $SOLUTION_NAME --configuration Release --warnaserror
 
     - name: Run tests
-      run: dotnet test $SOLUTION_PATH --configuration Release
+      run: dotnet test $SOLUTION_NAME --configuration Release
 
     - name: Dotnet format
       run: |
         dotnet tool install -g dotnet-format
-        dotnet format --verify-no-changes || echo "Format error. Execute dotnet format and commit again" && exit 1
+        dotnet format --verify-no-changes || echo "[!] You have format errors. Execute "dotnet format" and commit again" && exit 1
